### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#41]
I am not sure to understand how the algorithm is supposed to work but the example doesn't seem to work as expected.

```R
> # Detail of the hashing
> ## The main effect is hashed via `hash_h`
> all(hash_h(names(mapping)) %% 2^6 == mapping %% 2^6)
[1] TRUE
> ## The sign is corrected by `hash_xi`
> hash_xi(names(mapping))
 [1] -1  1  1 -1 -1  1 -1 -1  1  1  1  1 -1  1 -1  1  1  1
> ## The interaction term is implemented as follow:
> m2 <- hashed.model.matrix(~ .^2, CO2, 2^6, keep.hashing_mapping = TRUE)
> mapping2 <- unlist(as.list(attr(m2, "mapping")))
> mapping2[2] # PlantQn2:uptake
  PlantQn1 
3789462177 
> h1 <- mapping2["PlantQn2"]
> h2 <- mapping2["uptake"]
> library(pack)
> hash_h(rawToChar(c(numToRaw(h1, 4), numToRaw(h2, 4)))) # should be mapping2[2]
[1] 974267571
> h1
  PlantQn2 
4122940517 
> h2
    uptake 
1505155248 
> mapping2[2]
  PlantQn1 
3789462177 
```

Result of `hash_h` function is not `mapping2[2]`.

I want to update the important feature function I wrote for the package `xgboost` to take care of hashing trick but I am not able to reverse the splits in the trees to the orginal feature name and value (I am trying since half hour, so a bit new to the thing, I may miss something big).

One thing not related (and not enough important to deserve its own issue), I noticed that in the mapping you produce you paste the name of the data.frame column to the value. Why not separating them by a character like a point for an easier reading? There is the same behavior in `Matrix` package when doing one hot encoding... May be there is a reason I miss. 

Kind regards,
Michael

**Comment by wush978** [comment]
First of all, thanks for your report. 

The example is wrong because the `mapping2[2]` is not the hashed value of `PlantQn2:uptake`. I'll correct it in the next patch. 

The real implementation is shown in https://github.com/wush978/FeatureHashing/blob/cran-2015-01-01/src/hashed_model_matrix.cpp#L553

**Comment by wush978** [comment]
Sorry that I am not understand your statement related to `xgboost`. Do you mean that you used the hashing trick from this package before training a gdbt model and you want to reverse the hashing?

**Comment by pommedeterresautee** [comment]
@wush978 Thanks for your answers.

Regarding xgboost, I added to the R package several functions (only available on the Github version for now but soon to be published on Cran). One of them is about computing feature importance, the idea is to find which features are the most important to predict the label.

To make it interesting, I need to give back to the user the name of the original feature. In the trees generated by xgboost I have only an ID of the feature, then I use the sparse matrix column names to get back the value name. At the end the function is able to say to the user of xgboost that, for instance, Age < 30 is an important feature.

I wrote a Vignette here : https://github.com/tqchen/xgboost/blob/master/R-package/vignettes/discoverYourData.Rmd

Since a long time I look at Vowpal Wabbit wondering how I can do such thing in R. At the end of last year I saw your package but was too busy to make test. Now... I want to make it compliant with the new functions of Xgboost.

I will do some test this week with the new version you provided to me here and try to understand how I can do what I want to do :-)

Just a question, what is the advantage for a user of xgboost to use feature hashing compared to use a sparse one hot encoded matrix? IMO it is a kind of feature reduction but I am not sure. Is there something else (I am talking of classical case where the user doesn't push a stream of data which is not even possible right now on xgboost)? For a big Dataset, is your package rapid for the hashing? Is there some pick in memory use like for one hot encoding?

In Vowpal they say feature hashing is their special thing making every thing possible (which I understand for out of core algorithm), and my main question is would it be the case for xgboost?

Kind regards,
Michael

**Comment by pommedeterresautee** [comment]
For the documentation, the example in the README use a dataset not included in the package. I think it is not a good idea. It should be easy to reproduce which is not the case.

Kind regards,
Michaël

**Comment by wush978** [comment]
My reason of using hashing trick is usually for convenience. The `sparse.model.matrix` requires global information to encode the model matrix *consistently* and the global information is hard or expensive to get in streaming environment or distributed environment. With hashing trick, my code becomes simpler and I can spend my time on the other things such as modeling, feature selections, and algorithms. On our data, the accuracy affected by hashing trick is ignorable.

For example, the winner of Criteo's CTR challenge https://www.kaggle.com/c/criteo-display-ad-challenge/forums/t/10555/3-idiots-solution/55888#post55888 (The hashing trick do not contribute any improvement on the leaderboard. We
apply the hashing trick only because it makes our life easier to generate
features. :)) also uses the hashing trick to simplify their code.

Hope this information helps and thanks again for your suggestion. 

Wush

**Comment by pommedeterresautee** [comment]
@wush978 Thanks for these comments. It is very helpful. Your argument makes sense. I will post here my progress here in understanding your package.

**Comment by wush978** [comment]
c82506f82e206b1759cddc2678274fc4778d8688
