### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#45]
I deeply think this package deserves a Vignette as it is useful but not obvious in the way it works.

IMO the Vignette should start with a why Feature hashing. This link posted on Kaggle may be a source of inspiration:
http://webcache.googleusercontent.com/search?q=cache:PRrGZpsAUJAJ:metaoptimize.com/qa/questions/6943/what-is-the-hashing-trick+&cd=2&hl=en&ct=clnk&gl=us

Kind regards,
Michael

**Comment by pommedeterresautee** [comment]
For the CSS of the Vignette (if R markdown is choosen), we can use the one I made for xgboost:
https://github.com/tqchen/xgboost/tree/master/R-package/vignettes

**Comment by pommedeterresautee** [comment]
Something else I was wondering is if the distances between features in the reduced dimensions are kept in some way. According to the explanations in the link above it is the case.

**Comment by wush978** [comment]
Thanks for your suggestion and I agree with that.

I prefer enriching the content of REAMDE.Rmd first, then we could modify it as a vignette.

How do you think?

**Comment by pommedeterresautee** [comment]
README is not directly available to Cran users. Because it is not that hard to create an Rmarkdown Vignette I would first enrich the example in function documentation and asap there is enough content I would switch to the Vignette. Now, your turn... what do **YOU** think ? :-)

**Comment by wush978** [comment]
For the difference between README and vignette, I agree. But my point is that whether the patch of v0.8.1 should include vignette or not.

Currently, I am modifying the function `hashed.model.matrix` to make it more familiar to R users. I want to make the change available ASAP because these changes affect the default behavior and the existed code might not work after updating.

However, the vignette is less urgent because there is no compatibility issue.

If you agree, could you help me review the new `hashed.model.matrix` first? The main changing is #7 , #35 and #39. I am hesitant to make decision because there is no companion to discuss.

**Comment by wush978** [comment]
A less important issue of [milestone v0.8.1](https://github.com/wush978/FeatureHashing/milestones/CRAN%20v0.8.1) is #49.

**Comment by wush978** [comment]
Sorry that this goes off topic. I open a new issue #50 for reviewing the reason of changing API.

**Comment by pommedeterresautee** [comment]
I fully agree that the Vignette is not a necessity for the next version. 

I have posted some comments under the issue you referred too (I edited them too so don t take care of the one you may have received as email from github).

**Comment by pommedeterresautee** [comment]
Continue conversation on #60
