### ISSUE TITLE
Review of the new design of `hashed.model.matrix`

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#50]
Currently, I am modifying the function ‵hashed.model.matrix‵ to make it more familiar to R users. 

I am hesitant now because the new design is based on my own thinking. Therefore, it would be great if anyone can review the reason of the new design.

 The main changes are #7 , #35 and #39. A less important change is #49. Any comments and suggestions are welcome!

**Comment by pommedeterresautee** [comment]
In the pull request you will find a small detail to make the API even easier. I added support for direct column names instead of formula. It may help in source code examples to avoid using formula to make things even simpler and focus on the purpose of Feature hashing without having to explain other things like formula. 

Of course, Feature Hashing is powerful when you create new features by combining existing features and, in this case, formula is a nice interface. Having support for both is, IMHO, a good thing.

**Comment by wush978** [comment]
Thanks for your comments. It's nice to have a companion to review the design.

**Comment by pommedeterresautee** [comment]
It is nice to work with someone who cares about API design too :-)

**Comment by wush978** [comment]
These issues are all reviewed. Thanks for the help, @pommedeterresautee.
