### ISSUE TITLE
Add xgboost to Suggests

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#63]
Dear @pommedeterresautee ,

I saw you add the xgboost to the Suggests list but as far as I know the xgboost is recently removed from CRAN. <http://cran.r-project.org/web/packages/xgboost/index.html>.

Therefore, I prefer removing xgboost from Suggests list until it back to CRAN. Do you have any information about when the xgboost will back to CRAN?

Wush

**Comment by pommedeterresautee** [comment]
Oh I understand. 

We are in the process of re pushing to Cran since few weeks. We have cleaned almost all Cran check messages. I think it should be pushed in the following days/week. Tong He is in charge of this part. If nothing happens this week I will ask him.

Kind regards,
Michaël

**Comment by lewis-c** [comment]
Thanks both. I think this is also relevant to the vignettes if we wish to have an xgboost focus there. Many people would hesitate to use a package if it's not available on CRAN.

**Comment by pommedeterresautee** [comment]
It s enough easy to install with devtools to refer to it in a documentation. And it s a lot more rapid to learn huge dataset than glmnet. Feature Hashing makes sense in this use case.

However adding it in suggest is an issue because suggest is a field for Cran presentation so you expect to install the package from Cran.

That's why I would put it in documentation and not in suggest until it's added back to Cran.

Kind regards,
Michaël

**Comment by wush978** [comment]
Dear all,

I decide to remove both `glmnet` and `xgboost` from Suggests in v0.9 because there is no vignette in this version. The main reason is that I need to test the package in QEMU virtual machine for big endian issues. The requirement of `glmnet` and `xgboost` will significantly increase the time of testing.

The version v0.9.1 will require these two packages in the Suggests for vignette. I hope there is no modification of the core function, so I don't need to test the package in QEMU anymore.

Best,
Wush

**Comment by pommedeterresautee** [comment]
Very sorry for you you have to use QEMU. I have long bad story with it...
