### ISSUE TITLE
Does it have sense to have a hash size which is not a 2^x?

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#68]
From my understanding,hash size should be 2^x by definition. So it doesn t make sense to set a size like 45.
If I am right, a check should be added to hashed.model.matrix.
Implementing this test is easy to do (with log2).

Kind regards,
Michael

**Comment by wush978** [comment]
Dear Michael,

I prefer the power of 2 is because the implementation of the hashing function maps the features to the space {0, 1, 2, ..., 2^32} originally. If the hash size is the power of 2, then the density of the hashed result will be uniform if the hashing function is perfect. However, the density of the hashed result should be very close to the uniform distribution if the hash size is 45. Therefore, I don't prefer limiting the hash size like this. It is only required to be a positive integer and smaller than 2^32.

Best,
Wush

**Comment by pommedeterresautee** [comment]
Ok thanks a lot for the explanation!
